export PATH="/Users/walfits/Repositories/plumed2/src/lib/:$PATH"
export LIBRARY_PATH="/Users/walfits/Repositories/plumed2/src/lib/:$LIBRARY_PATH"
export LD_LIBRARY_PATH="/Users/walfits/Repositories/plumed2/src/lib/:$LD_LIBRARY_PATH"
export DYLD_LIBRARY_PATH="/Users/walfits/Repositories/plumed2/src/lib/:$DYLD_LIBRARY_PATH"
export PLUMED_KERNEL="/Users/walfits/Repositories/plumed2/src/lib/libplumedKernel.dylib"
export PLUMED_VIMPATH="/Users/walfits/Repositories/plumed2/vim"
